# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_hour_best_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
