# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_auto_20160404_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(unique=True)),
                ('reddit_post_id', models.CharField(blank=True, max_length=20, null=True)),
                ('reddit_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hour',
            name='best_of',
            field=models.BooleanField(default=False, help_text='Indicates this is a Best Of show, which is a compliation of segments from previous shows.'),
        ),
        migrations.AlterField(
            model_name='hour',
            name='description',
            field=models.CharField(help_text='A longer description of this segment. Only shown in day view.', max_length=500),
        ),
        migrations.AlterField(
            model_name='hour',
            name='link',
            field=models.URLField(blank=True, help_text='Download URL', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='hour',
            name='summary',
            field=models.CharField(help_text='NOT CURRENTLY USED', max_length=500),
        ),
        migrations.AlterField(
            model_name='hour',
            name='title',
            field=models.CharField(help_text='A short title for this segment. Shown in calendar view.', max_length=600),
        ),
        migrations.AddField(
            model_name='hour',
            name='air_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcasts.AirDate'),
        ),
    ]
