# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_auto_20161215_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hour',
            options={'get_latest_by': 'pub_date', 'ordering': ['pub_date']},
        ),
        migrations.AddField(
            model_name='hour',
            name='tweeted',
            field=models.BooleanField(default=False, help_text='Indicates whether a tweet has been sent out announcing this hour.'),
        ),
    ]
